### ISSUE TITLE
Bug when "sorotoki --test"

### ISSUE THREAD

**Issue by StevenHat** [BJCaasenbrood/SorotokiFem#1]
When it comes to "Running meshTest .........", it defeat. The warning is "MATLAB:UndefinedFunction", and it said that i haven't the function 'LocalsNHFast_mex'. I finally found it in "\sorotokicode\lib\sorotokifem\mex\localsNH\" and it's "LocalsNHFast_mex.mexa64", which can't be recognized by Windows system.
Could you provide a mexw64 type，or do you have any other way for me to run it^_^
Thank you~

**Comment by BJCaasenbrood** [comment]
He Steven,

You cannot run SorotokiFem as a separate module, you need to install sorotoki as a complete package.

Did you follow the installation guide:
 https://bjcaasenbrood.github.io/SorotokiCode/install/

ps. MPM is now called MPI. So you need to write 'mpi install sorotokicode' instead.

**Comment by BJCaasenbrood** [comment]
Also make sure it is loaded into Matlab's path and that you build these mex files yourself using 'sorotoki build'. 

If done correctly, installing sorotoki should add these folders to your search path. If not, you can manually add them using 'addpath(genpath(PATH))'

**Comment by StevenHat** [comment]
Thank you for your reply~
I follow the installation guide. When I use 'mpi' instead of 'mpm', many errors will occur during the installation process. The first error is：`Error in sorotoki (line 58)
    assert(~strcmpi(mpmPath(1:5),'build'), msg('mpm_not_installed'));`
, which is because the code in line 58 `mpmPath = which('mpm');` is looking for 'mpm' instead of 'mpi'.
When I modify the code here to `mpmPath = which('mpi');`, more similar errors will appear.
When I copy 'mpi.m' to 'mpm.m', it works, but still fails when I try to run 'sorotoki build'. The following txt records the entire process of this attempt:
[window.txt](https://github.com/BJCaasenbrood/SorotokiFem/files/14397259/window.txt)
and the last error(representative) is as follows:
[fail.txt](https://github.com/BJCaasenbrood/SorotokiFem/files/14397279/fail.txt)

I have tried using an old version of MPM(V3.2.0) and the results are the same.

That's why I'm looking for 'LocalsNHFast_mex.mexw64'.

**Comment by StevenHat** [comment]
By the way, my operating system is Windows. 
:D

**Comment by BJCaasenbrood** [comment]
I see, I've checked your `windows.txt` log and do see the error. The command `sorotoki build` will build the mex files that are currently missing for you; and they are (often) system specific that is why I recommended to build them yourself. 

When calling `sorotoki build`, the mex builder fails to build `LocalsNHFast_mex.mexaw64`, `LocalsYHFast_mex.mexaw64`, `curveSweepModifierFast_mex.mexaw64`, and `computeForwardKinematicsGaussFast_mex.mexaw64`. I see the error message `Function '...' not supported for code generation.` in the `windows.txt` file (not really insightful to track down the error).

On the other hand, `lagrangian_mex.mexaw64` does build correctly.... 

Can you try navigating to `D:\APP\Matlab\toolbox\mpm-master\mpm-master\mpi-packages\sorotokicode\lib\sorotokifem\mex\localsNH` and try running `generateMexLNH.m`. Does it give a detailed error?

**Comment by StevenHat** [comment]
Yeah, the error is:
Function 'LocalsNHFast' not supported for code generation.
More information
Code generation failed: View Error Report

Error using codegen

Error in generateMexLNH (line 9)
codegen -silent -config cfg LocalsNHFast ...

**Comment by BJCaasenbrood** [comment]
and if you remove `-silent -config cfg` in `generateMexLNH.m`

**Comment by StevenHat** [comment]
the same

**Comment by StevenHat** [comment]
>> generateMexLNH
Function 'LocalsNHFast' not supported for code generation.
More information
Code generation failed: View Error Report

Error using codegen


Error in generateMexLNH (line 9)
codegen LocalsNHFast ...

**Comment by BJCaasenbrood** [comment]
what does the `View Error Report` say? If you click it?

**Comment by StevenHat** [comment]
It pointed to a window
![error](https://github.com/BJCaasenbrood/SorotokiFem/assets/71592790/9d7217f6-6449-4f1a-911c-e5fc9c7bb906)

**Comment by BJCaasenbrood** [comment]
I am kinda puzzled tbh, `Function not supported for code generation`... But why 🥲. Maybe try running this code just in the command window:

```matlab
codegen LocalsNHFast -args {coder.typeof(10,[inf,inf]), coder.typeof(10,[inf,inf]), coder.typeof(10,[1,1]), coder.typeof(10,[1,1]), coder.typeof(10,[1,1]), coder.typeof(10,[inf,inf]), coder.typeof(10,[inf,1,inf]), coder.typeof(10,[inf,inf,inf]), coder.typeof(10,[inf,1]), coder.typeof(10,[inf,inf]), coder.typeof(10,[inf,inf]), coder.typeof(10,[1,1]), coder.typeof(10,[1,1]), coder.typeof(10,[inf,1]), coder.typeof(10,[1,1]), coder.typeof(10,[1,1])}
```

**Comment by BJCaasenbrood** [comment]
I also found this: https://nl.mathworks.com/help/coder/ug/function-is-not-supported-for-code-generation.html It is the same error you get. 

Maybe also add `-report` argument (between `LocalsNHFast` and `-args`) to see which MATLAB function it is struggling with.

**Comment by StevenHat** [comment]
Haha, Do you mean to execute it from the Matlab command line? it still fails.

> I am kinda puzzled tbh, `Function not supported for code generation`... But why 🥲. Maybe try running this code just in the command window:
> 
> ```matlab
> codegen LocalsNHFast -args {coder.typeof(10,[inf,inf]), coder.typeof(10,[inf,inf]), coder.typeof(10,[1,1]), coder.typeof(10,[1,1]), coder.typeof(10,[1,1]), coder.typeof(10,[inf,inf]), coder.typeof(10,[inf,1,inf]), coder.typeof(10,[inf,inf,inf]), coder.typeof(10,[inf,1]), coder.typeof(10,[inf,inf]), coder.typeof(10,[inf,inf]), coder.typeof(10,[1,1]), coder.typeof(10,[1,1]), coder.typeof(10,[inf,1]), coder.typeof(10,[1,1]), coder.typeof(10,[1,1])}
> ```

**Comment by StevenHat** [comment]
> I also found this: https://nl.mathworks.com/help/coder/ug/function-is-not-supported-for-code-generation.html It is the same error you get.
> 
> Maybe also add `-report` argument (between `LocalsNHFast` and `-args`) to see which MATLAB function it is struggling with.

add 'report' like this?
![1](https://github.com/BJCaasenbrood/SorotokiFem/assets/71592790/eeed40fe-9c9d-412e-b748-9af427163961)
:[
![2](https://github.com/BJCaasenbrood/SorotokiFem/assets/71592790/dc4b625c-82a0-4b44-883b-11c4575d4f6b)

**Comment by BJCaasenbrood** [comment]
This is really frustrating, I am sorry. My best guess is that MATLAB refuses to build the code due to some function it does not want to convert to `c++` executable code. Which MATLAB version are you running?

Maybe we can plan a meeting on Discord tomorrow, and we can check together to make it work.

**Comment by StevenHat** [comment]
> This is really frustrating, I am sorry. My best guess is that MATLAB refuses to build the code due to some function it does not want to convert to `c++` executable code. Which MATLAB version are you running?
> 
> Maybe we can plan a meeting on Discord tomorrow, and we can check together to make it work.

R2023b.
Okay~

**Comment by BJCaasenbrood** [comment]
https://discord.gg/u6CWsjPsyG (you can join the Discord group here)

**Comment by BJCaasenbrood** [comment]
Okay, fixed the issue. When MPM or MPI is installed under the `Matlab/toolbox/` directory, the Matlab Coder refuses to build any mex executables. Hence, make sure that the mpm/mpi packages is installed either under the `Matlab Add-ons` folder of `Documents/MATLAB/` folder.

**Comment by BJCaasenbrood** [comment]
MPM installer issue(s) due to MPI renaming has been fixed in the following: https://github.com/BJCaasenbrood/SorotokiCode/commit/f96ddb7691c47c0b9c9398a2a9ab28fcc24a5468
